### ISSUE TITLE
Program doesn't run from codeblocks

### ISSUE THREAD

**Issue by sbarili** [holdenAtCU/Sheftel_CSCI2270_FinalProject#1]
+//the program doens't run from codeblocks--there is an error "#this file requires compiler and library support for the ISO 2011 c++ standard.
+//I don't believe there is any bug in your code but I couldn't run it to double check.
//also, sorry I added a new issues.md file to your project repo, I misunderstood directions.

**Comment by holdenout** [comment]
In Code::Blocks, try going to Settings->Compiler, and then make sure that "Have g++ follow the C++11 ISO C++ language standard [-std=c++11]" is checked off. Let me know if that works.

In terms of the added issue.md file, it won't be added unless you submit a pull request, which is then accepted by me.

**Comment by sbarili** [comment]
I got it working, thanks for that!
